version: '3'

services:
  web:
    build: ./app
    networks:
      - app
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://tsoha:tsoha@db/tsoha
    depends_on:
      - db
  migrate:
    build: ./migrate
    networks:
      - app
    volumes:
      - ./migrate/conf:/flyway/conf
      - ./migrate/sql:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=tsoha
      - POSTGRES_PASSWORD=tsoha
    ports:
      - 5432:5432
    networks:
      - app
networks:
  app:
